name: Deploy Search-Application+searchdl

on:
  # workflow_run:
  #   branches:
  #     - master
  #   workflows: ["Container Build and Push"]
  #   types:
  #     - completed
  workflow_dispatch: # Allow manual runs
    inputs:
      branch:
        description: "Branch to trigger in searchdl"
        required: true
        default: "main"

jobs:
  deploy-to-dev:
    name: Deploy Search-Application to DEV
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: vineeth12345/workflows/.github/workflows/search-app.yml@main
    secrets: inherit
    concurrency: Development-inttest01 # Match environment-name below for deployments
    with:
      environment-name: Development-inttest01
      operation: deploy
      environment-type: DEV
      instance-name: inttest01

  trigger-searchdl:
    name: Trigger Deployment for SearchDL
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SearchDL Deployment
        uses: actions/github-script@v6
        with:
          script: |
            const github = require('@actions/github');  // Add this line to explicitly import github
            const core = require('@actions/core');  // Import core for handling inputs
            const branch = core.getInput('branch');
            const response = await github.rest.repos.createWorkflowDispatch({
              owner: 'vineeth12345',
              repo: 'docker_catcg_poc',
              workflow_id: 'deploy1.yml', // Workflow file in the docker_catcg_poc repo
              ref: branch,
              inputs: {
                environment_name: "Development-inttest01",
                operation: "deploy",
                environment_type: "DEV",
                "instance-name": "inttest01"
              }
            });
            console.log('Triggered workflow in searchdl:', response.status);
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
