name: Deploy Search-Application+searchdl

on:
  workflow_dispatch: # Allows manual runs
    inputs:
      branch:
        description: "Branch to trigger in searchdl"
        required: true
        default: "main"

jobs:
  deploy-to-dev:
    name: Deploy Search-Application to DEV
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: vineeth12345/workflows/.github/workflows/search-app.yml@main # Reference to the reusable workflow
    secrets: inherit
    concurrency: Development-inttest01 # Match environment-name below for deployments
    with:
      environment-name: Development-inttest01
      operation: deploy
      environment-type: DEV
      instance-name: inttest01

  trigger-searchdl:
    name: Trigger Deployment for SearchDL
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SearchDL Deployment via GitHub API (curl)
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/vineeth12345/docker_catcg_poc/actions/workflows/deploy1.yml/dispatches \
            -d '{
              "ref": "refs/heads/${{ github.event.inputs.branch }}",
              "inputs": {
              }
            }')

          if [[ "$RESPONSE" -eq 204 ]]; then
            echo "Success: Triggered SearchDL deployment successfully." | tee -a $GITHUB_STEP_SUMMARY
          else
            echo "Error: Failed to trigger SearchDL deployment. HTTP Response: $RESPONSE" | tee -a $GITHUB_STEP_SUMMARY
            echo "Response Details:" | tee -a $GITHUB_STEP_SUMMARY
            cat response.txt | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

        # curl -L \
        #   -X POST \
        #   -H "Accept: application/vnd.github+json" \
        #   -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
        #   -H "X-GitHub-Api-Version: 2022-11-28" \
        #   https://api.github.com/repos/vineeth12345/docker_catcg_poc/actions/workflows/deploy1.yml/dispatches \
        #   -d '{
        #     "ref": "refs/heads/${{ github.event.inputs.branch }}",
        #     "inputs": {
        #     }
        #   }'
