name: Deploy Search-Application+searchdl

on:
  workflow_dispatch: # Allows manual runs
    inputs:
      branch:
        description: "Branch to trigger in searchdl"
        required: true
        default: "main"

jobs:
  deploy-to-dev:
    name: Deploy Search-Application to DEV
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: vineeth12345/workflows/.github/workflows/search-app.yml@main # Reference to the reusable workflow
    secrets: inherit
    concurrency: Development-inttest01 # Match environment-name below for deployments
    with:
      environment-name: Development-inttest01
      operation: deploy
      environment-type: DEV
      instance-name: inttest01

  trigger-searchdl:
    name: Trigger Deployment for SearchDL
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SearchDL Deployment via GitHub API (curl)
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/vineeth12345/searchdl/actions/workflows/deploy1.yml/dispatches \
            -d '{
              "ref": "refs/heads/${{ github.event.inputs.branch }}",
              "inputs": {
                "environment_name": "Development-inttest01",
                "operation": "deploy",
                "environment_type": "DEV",
                "instance-name": "inttest01"
              }
            }'
