name: Deploy Search-Application+searchdl

on:
  workflow_dispatch: # Allows manual runs
    inputs:
      branch:
        description: "Branch to trigger in searchdl"
        required: true
        default: "main"

jobs:
  deploy-to-dev:
    name: Deploy Search-Application to DEV
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: vineeth12345/workflows/.github/workflows/search-app.yml@main # This line needs to be corrected
    secrets: inherit
    concurrency: Development-inttest01 # Match environment-name below for deployments
    with:
      environment-name: Development-inttest01
      operation: deploy
      environment-type: DEV
      instance-name: inttest01

  trigger-searchdl:
    name: Trigger Deployment for SearchDL
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    steps:
      - name: Trigger SearchDL Deployment
        uses: peter-evans/workflow-dispatch@v3
        with:
          repository: vineeth12345/searchdl # Replace with the actual username/repo name
          workflow: deploy1.yml # Workflow file name in Repo B
          ref: refs/heads/${{ github.event.inputs.branch }} # Use the input branch here
          inputs:
            environment_name: "Development-inttest01"
            operation: "deploy"
            environment_type: "DEV"
            instance-name: "inttest01"
